
package com.novatec.services.folderservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ItemExistsException", targetNamespace = "http://ws.openkm.com")
public class ItemExistsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ItemExistsException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ItemExistsException_Exception(String message, ItemExistsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ItemExistsException_Exception(String message, ItemExistsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.novatec.services.folderservice.ItemExistsException
     */
    public ItemExistsException getFaultInfo() {
        return faultInfo;
    }

}
