
package com.novatec.services.folderservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OKMFolder", targetNamespace = "http://ws.openkm.com", wsdlLocation = "http://192.168.1.5:8086/OpenKM/services/OKMFolder?wsdl")
public class OKMFolder_Service
    extends Service
{

    private final static URL OKMFOLDER_WSDL_LOCATION;
    private final static WebServiceException OKMFOLDER_EXCEPTION;
    private final static QName OKMFOLDER_QNAME = new QName("http://ws.openkm.com", "OKMFolder");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.5:8086/OpenKM/services/OKMFolder?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OKMFOLDER_WSDL_LOCATION = url;
        OKMFOLDER_EXCEPTION = e;
    }

    public OKMFolder_Service() {
        super(__getWsdlLocation(), OKMFOLDER_QNAME);
    }

    public OKMFolder_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OKMFOLDER_QNAME, features);
    }

    public OKMFolder_Service(URL wsdlLocation) {
        super(wsdlLocation, OKMFOLDER_QNAME);
    }

    public OKMFolder_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OKMFOLDER_QNAME, features);
    }

    public OKMFolder_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OKMFolder_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OKMFolder
     */
    @WebEndpoint(name = "OKMFolderPort")
    public OKMFolder getOKMFolderPort() {
        return super.getPort(new QName("http://ws.openkm.com", "OKMFolderPort"), OKMFolder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OKMFolder
     */
    @WebEndpoint(name = "OKMFolderPort")
    public OKMFolder getOKMFolderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.openkm.com", "OKMFolderPort"), OKMFolder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OKMFOLDER_EXCEPTION!= null) {
            throw OKMFOLDER_EXCEPTION;
        }
        return OKMFOLDER_WSDL_LOCATION;
    }

}
