
package com.novatec.services.authservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OKMAuth", targetNamespace = "http://ws.openkm.com", wsdlLocation = "http://192.168.1.5:8086/OpenKM/services/OKMAuth?wsdl")
public class OKMAuth_Service
    extends Service
{

    private final static URL OKMAUTH_WSDL_LOCATION;
    private final static WebServiceException OKMAUTH_EXCEPTION;
    private final static QName OKMAUTH_QNAME = new QName("http://ws.openkm.com", "OKMAuth");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.5:8086/OpenKM/services/OKMAuth?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OKMAUTH_WSDL_LOCATION = url;
        OKMAUTH_EXCEPTION = e;
    }

    public OKMAuth_Service() {
        super(__getWsdlLocation(), OKMAUTH_QNAME);
    }

    public OKMAuth_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OKMAUTH_QNAME, features);
    }

    public OKMAuth_Service(URL wsdlLocation) {
        super(wsdlLocation, OKMAUTH_QNAME);
    }

    public OKMAuth_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OKMAUTH_QNAME, features);
    }

    public OKMAuth_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OKMAuth_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OKMAuth
     */
    @WebEndpoint(name = "OKMAuthPort")
    public OKMAuth getOKMAuthPort() {
        return super.getPort(new QName("http://ws.openkm.com", "OKMAuthPort"), OKMAuth.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OKMAuth
     */
    @WebEndpoint(name = "OKMAuthPort")
    public OKMAuth getOKMAuthPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.openkm.com", "OKMAuthPort"), OKMAuth.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OKMAUTH_EXCEPTION!= null) {
            throw OKMAUTH_EXCEPTION;
        }
        return OKMAUTH_WSDL_LOCATION;
    }

}
