
package com.novatec.services.documentservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UnsupportedMimeTypeException", targetNamespace = "http://ws.openkm.com")
public class UnsupportedMimeTypeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnsupportedMimeTypeException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UnsupportedMimeTypeException_Exception(String message, UnsupportedMimeTypeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UnsupportedMimeTypeException_Exception(String message, UnsupportedMimeTypeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.novatec.services.documentservice.UnsupportedMimeTypeException
     */
    public UnsupportedMimeTypeException getFaultInfo() {
        return faultInfo;
    }

}
