
package com.novatec.services.propertyservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AccessDeniedException", targetNamespace = "http://ws.openkm.com")
public class AccessDeniedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AccessDeniedException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AccessDeniedException_Exception(String message, AccessDeniedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AccessDeniedException_Exception(String message, AccessDeniedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.novatec.services.propertyservice.AccessDeniedException
     */
    public AccessDeniedException getFaultInfo() {
        return faultInfo;
    }

}
