
package com.novatec.services.propertyservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "VersionException", targetNamespace = "http://ws.openkm.com")
public class VersionException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private VersionException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public VersionException_Exception(String message, VersionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public VersionException_Exception(String message, VersionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.novatec.services.propertyservice.VersionException
     */
    public VersionException getFaultInfo() {
        return faultInfo;
    }

}
