
package com.novatec.services.searchservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OKMSearch", targetNamespace = "http://ws.openkm.com", wsdlLocation = "http://192.168.1.5:8086/OpenKM/services/OKMSearch?wsdl")
public class OKMSearch_Service
    extends Service
{

    private final static URL OKMSEARCH_WSDL_LOCATION;
    private final static WebServiceException OKMSEARCH_EXCEPTION;
    private final static QName OKMSEARCH_QNAME = new QName("http://ws.openkm.com", "OKMSearch");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.5:8086/OpenKM/services/OKMSearch?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OKMSEARCH_WSDL_LOCATION = url;
        OKMSEARCH_EXCEPTION = e;
    }

    public OKMSearch_Service() {
        super(__getWsdlLocation(), OKMSEARCH_QNAME);
    }

    public OKMSearch_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OKMSEARCH_QNAME, features);
    }

    public OKMSearch_Service(URL wsdlLocation) {
        super(wsdlLocation, OKMSEARCH_QNAME);
    }

    public OKMSearch_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OKMSEARCH_QNAME, features);
    }

    public OKMSearch_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OKMSearch_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OKMSearch
     */
    @WebEndpoint(name = "OKMSearchPort")
    public OKMSearch getOKMSearchPort() {
        return super.getPort(new QName("http://ws.openkm.com", "OKMSearchPort"), OKMSearch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OKMSearch
     */
    @WebEndpoint(name = "OKMSearchPort")
    public OKMSearch getOKMSearchPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.openkm.com", "OKMSearchPort"), OKMSearch.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OKMSEARCH_EXCEPTION!= null) {
            throw OKMSEARCH_EXCEPTION;
        }
        return OKMSEARCH_WSDL_LOCATION;
    }

}
