
package com.novatec.services.bookmarkservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OKMBookmark", targetNamespace = "http://ws.openkm.com", wsdlLocation = "http://192.168.1.5:8086/OpenKM/services/OKMBookmark?wsdl")
public class OKMBookmark_Service
    extends Service
{

    private final static URL OKMBOOKMARK_WSDL_LOCATION;
    private final static WebServiceException OKMBOOKMARK_EXCEPTION;
    private final static QName OKMBOOKMARK_QNAME = new QName("http://ws.openkm.com", "OKMBookmark");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.5:8086/OpenKM/services/OKMBookmark?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OKMBOOKMARK_WSDL_LOCATION = url;
        OKMBOOKMARK_EXCEPTION = e;
    }

    public OKMBookmark_Service() {
        super(__getWsdlLocation(), OKMBOOKMARK_QNAME);
    }

    public OKMBookmark_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OKMBOOKMARK_QNAME, features);
    }

    public OKMBookmark_Service(URL wsdlLocation) {
        super(wsdlLocation, OKMBOOKMARK_QNAME);
    }

    public OKMBookmark_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OKMBOOKMARK_QNAME, features);
    }

    public OKMBookmark_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OKMBookmark_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OKMBookmark
     */
    @WebEndpoint(name = "OKMBookmarkPort")
    public OKMBookmark getOKMBookmarkPort() {
        return super.getPort(new QName("http://ws.openkm.com", "OKMBookmarkPort"), OKMBookmark.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OKMBookmark
     */
    @WebEndpoint(name = "OKMBookmarkPort")
    public OKMBookmark getOKMBookmarkPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.openkm.com", "OKMBookmarkPort"), OKMBookmark.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OKMBOOKMARK_EXCEPTION!= null) {
            throw OKMBOOKMARK_EXCEPTION;
        }
        return OKMBOOKMARK_WSDL_LOCATION;
    }

}
