
package com.novatec.services.repositoryservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OKMRepository", targetNamespace = "http://ws.openkm.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OKMRepository {


    /**
     * 
     * @param token
     * @param uuid
     * @return
     *     returns java.lang.String
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNodePath", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetNodePath")
    @ResponseWrapper(localName = "getNodePathResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetNodePathResponse")
    public String getNodePath(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "uuid", targetNamespace = "")
        String uuid)
        throws DatabaseException_Exception, PathNotFoundException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @param path
     * @return
     *     returns java.lang.String
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNodeUuid", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetNodeUuid")
    @ResponseWrapper(localName = "getNodeUuidResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetNodeUuidResponse")
    public String getNodeUuid(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "path", targetNamespace = "")
        String path)
        throws DatabaseException_Exception, PathNotFoundException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @return
     *     returns com.novatec.services.repositoryservice.Folder
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTemplatesFolder", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetTemplatesFolder")
    @ResponseWrapper(localName = "getTemplatesFolderResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetTemplatesFolderResponse")
    public Folder getTemplatesFolder(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws DatabaseException_Exception, PathNotFoundException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @throws AccessDeniedException_Exception
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     * @throws LockException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "purgeTrash", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.PurgeTrash")
    @ResponseWrapper(localName = "purgeTrashResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.PurgeTrashResponse")
    public void purgeTrash(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws AccessDeniedException_Exception, DatabaseException_Exception, LockException_Exception, PathNotFoundException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @return
     *     returns com.novatec.services.repositoryservice.Folder
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMailFolder", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetMailFolder")
    @ResponseWrapper(localName = "getMailFolderResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetMailFolderResponse")
    public Folder getMailFolder(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws DatabaseException_Exception, PathNotFoundException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @return
     *     returns com.novatec.services.repositoryservice.Folder
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonalFolder", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetPersonalFolder")
    @ResponseWrapper(localName = "getPersonalFolderResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetPersonalFolderResponse")
    public Folder getPersonalFolder(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws DatabaseException_Exception, PathNotFoundException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @return
     *     returns com.novatec.services.repositoryservice.Folder
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getThesaurusFolder", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetThesaurusFolder")
    @ResponseWrapper(localName = "getThesaurusFolderResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetThesaurusFolderResponse")
    public Folder getThesaurusFolder(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws DatabaseException_Exception, PathNotFoundException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @param path
     * @return
     *     returns boolean
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hasNode", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.HasNode")
    @ResponseWrapper(localName = "hasNodeResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.HasNodeResponse")
    public boolean hasNode(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "path", targetNamespace = "")
        String path)
        throws DatabaseException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @return
     *     returns com.novatec.services.repositoryservice.Folder
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRootFolder", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetRootFolder")
    @ResponseWrapper(localName = "getRootFolderResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetRootFolderResponse")
    public Folder getRootFolder(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws DatabaseException_Exception, PathNotFoundException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @return
     *     returns com.novatec.services.repositoryservice.AppVersion
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAppVersion", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetAppVersion")
    @ResponseWrapper(localName = "getAppVersionResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetAppVersionResponse")
    public AppVersion getAppVersion(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws DatabaseException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @return
     *     returns com.novatec.services.repositoryservice.Folder
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTrashFolder", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetTrashFolder")
    @ResponseWrapper(localName = "getTrashFolderResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetTrashFolderResponse")
    public Folder getTrashFolder(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws DatabaseException_Exception, PathNotFoundException_Exception, RepositoryException_Exception
    ;

    /**
     * 
     * @param token
     * @return
     *     returns com.novatec.services.repositoryservice.Folder
     * @throws RepositoryException_Exception
     * @throws DatabaseException_Exception
     * @throws PathNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoriesFolder", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetCategoriesFolder")
    @ResponseWrapper(localName = "getCategoriesFolderResponse", targetNamespace = "http://ws.openkm.com", className = "com.novatec.services.repositoryservice.GetCategoriesFolderResponse")
    public Folder getCategoriesFolder(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws DatabaseException_Exception, PathNotFoundException_Exception, RepositoryException_Exception
    ;

}
